# Download offline package
download:
  # 离线包保存目录，节点安装包从该目录拷贝
  dest: /Users/mingday/.ansible/workspace/ansible-deploy-k8s-binary/k8s/binary

  # 下载超时时间
  timeout: 60
  # 重试次数
  retries: 4
  # 重试的时间间隔
  retry_stagger: 5

# 基础资源清单文件，以及helm chart存放位置
k8s_manifests_dir: /etc/kubernetes/manifests

# kubeconfig文件路径
kubeconfig: /root/.kube/config

# # NTP Settings
# ntp:
#   # 需要自定义NTP服务器时需设置为true
#   manage_config: false
#   servers:
#     - "ntp1.aliyun.com iburst"
#     - "ntp2.aliyun.com iburst"
#     - "ntp3.aliyun.com iburst"
#     - "ntp4.aliyun.com iburst"

# 外部storageClass
storage_class_name: local-path

# 镜像仓库源
registry:
  external_registry_enable: false
  external_registry_url: docker.io
  local_registry_url: registry.local:5000


# Repository 软件源
repo:
  # 建议使用nexus配置代理使用
  nvidia_container_toolkit_centos: "https://nvidia.github.io/libnvidia-container/stable/rpm/$basearch"
  nvidia_container_toolkit_ubuntu: "deb https://nvidia.github.io/libnvidia-container/stable/deb/$(ARCH) /"

# Kubernetes Cert
cert:
  # 签发集群整数保存目录，默认签发10年有限期证书
  dir: /Users/mingday/.ansible/workspace/ansible-deploy-k8s-binary/k8s/certs
  # 签发证书大小
  size: 2048
  # 签发证书的时间
  day: 3650d

# https://github.com/etcd-io/etcd
etcd:
  # etcd 版本
  version: v3.5.17
  # etcd 数据目录，如使用多个目录映射同一块数据盘的方式，请勿修改默认目录
  data_dir: "/var/lib/etcd"

# High Availability
# kube-apiserver负载均衡的信息
# 如使用haproxy + keepalived请填写VIP及端口
# 如使用公有云负载均衡请填写负载均衡IP及端口（需再安装之前自行配置）
# 如使用域名，需提前配置解析。不使用域名时，请注释掉
# 如使用haproxy + keepalived ，并且跟master节点部署在一起时，请修改port以避免端口冲突
loadbalance:
  ip: 10.20.183.88
  port: 8443
  # domain_name: apiserver.kubeop.com
  # access_ip:
  #   - 172.16.90.100

# https://github.com/kubernetes/kubernetes
kubernetes:
  # kubernetes 版本
  version: v1.31.4
  # 集群Pod网段
  pods_subnet: 172.18.0.0/16
  # 集群Service网段
  service_addresses: 10.64.0.0/16
  # 节点Pod网段掩码大小
  node_prefix: 25
  # 节点最大Pod数量
  kubelet_max_pods: 110
  # kubelet 数据目录，如使用多个目录映射同一块数据盘的方式，请勿修改默认目录
  kubelet_dir: "/var/lib/kubelet"
  # kube-proxy模式，支持iptables和ipvs
  kube_proxy_mode: ipvs
  # 配置kube-proxy的ipvs调度策略，支持rr(轮询),wrr(加权轮训),lc(最少连接数),wlc(加权最少连接数),sh(源地址哈希),dh(目标地址哈希),sed(最短预期延迟),nq(最少队列)
  scheduler: rr
  # 使用 MetalLB、kube-vip 必须设置为 true 才能正常工作
  strict_arp: false

# https://github.com/opencontainers/runc
runc:
  # runc 版本
  version: v1.2.3

# https://github.com/containernetworking/plugins
cniplugins:
  # cni-plugins 版本
  version: v1.6.1

# https://github.com/kubernetes-sigs/cri-tools
critools:
  # cri-tools 版本
  version: v1.32.0

# https://github.com/containerd/nerdctl
nerdctl:
  # nerdctl 版本
  version: v2.0.2

# https://github.com/helm/helm
helm:
  # helm 版本
  version: v3.16.4

# https://github.com/containerd/containerd
containerd:
  # containerd 版本,建议使用1.6.x版本(1.6.x当前为长期稳定版本)
  version: 2.0.1
  # containerd 持久化数据目录，如使用多个目录映射同一块数据盘的方式，请勿修改默认目录
  root: "/var/lib/containerd"
  # containerd 临时数据目录
  state: "/run/containerd"
  # containerd oom_score
  oom_score: -999
  grpc:
    max_recv_message_size: 16777216
    max_send_message_size: 16777216
  debug:
    level: ""
  metrics:
    address: ""
    grpc_histogram: false
  cri:
    sandbox_image: "registry.local:5000/pause:3.9"
    max_concurrent_downloads: 3
    max_container_log_line_size: -1
  containerd:
    snapshotter: overlayfs
  options:
    SystemdCgroup: true
  registries:
    "docker.io": "https://registry-1.docker.io"
    "registry.k8s.io": "https://registry.k8s.io"

# Network Plugin
network_plugin: cilium
# cilium need linux kernel >= 4.9.17
cilium:
  # https://github.com/cilium/cilium
  version: v1.16.1
  # {{cilium.registry}}/operator-generic:{{cilium.version}}
  # {{cilium.registry}}/cilium:{{cilium.version}}
  registry: registry.local:5000/cilium
  # "disabled" or "vxlan" or "geneve"
  network_mode: vxlan

flannel:
  # https://github.com/flannel-io/flannel
  version: v0.25.7
  plugin_version: v1.5.1-flannel3
  # {{flannel.registry}}/flannel-cni-plugin:{{flannel.plugin_version}}
  # {{flannel.registry}}/flannel:{{flannel.version}}
  registry: registry.local:5000/flannel
  # "vxlan" or "host-gw"
  network_mode: vxlan
  # 运行参数
  args:
    - "--ip-masq"
    - "--kube-subnet-mgr"
  # 当主机位于同一子网上时启用直接路由
  directRouting: false
  # 传出数据包的所需 MTU，如果未定义，则使用外部接口的 MTU。
  # mtu: 1500

calico:
  # https://github.com/projectcalico/calico
  version: v3.27.3
  # {{calico.registry}}/kube-controllers:{{calico.version}}
  # {{calico.registry}}/node:{{calico.version}}
  # {{calico.registry}}/cni:{{calico.version}}
  registry: registry.local:5000/calico
  # "ipip" or "bgp" or "mix"
  network_mode: ipip
  # mtu 默认为0，表示自动自动检测
  mtu: 0
  # 可指定网卡interface=eth.*或使用can-reach=网关
  ip_autodetection_method: interface=ens192

kuberouter:
  # https://github.com/cloudnativelabs/kube-router
  version: v1.6.1
  # {{kube-router.registry}}/kube-router
  registry: registry.local:5000/cloudnativelabs
  # Setups node CNI to allow hairpin mode, requires node reboots, see
  # https://github.com/cloudnativelabs/kube-router/blob/master/docs/user-guide.md#hairpin-mode
  # 即让Pod可以通过Service访问自己
  hairpin_mode: true
  # 启用Pod网络，通过iBGP通告和学习到Pod的路由
  run_router: true
  # 启用网络策略，设置iptables为Pod提供入口防火墙
  run_firewall: true
  # 启用服务代理，为Kubernetes服务设置IPVS
  run_service_proxy: false

# Addons
coredns:
  version: 1.11.1
  # {{coredns.registry}}/coredns:{{coredns.version}}
  registry: registry.local:5000/coredns
nodelocaldns:
  enabled: true
  version: 1.23.0
  # {{nodelocaldns.registry}}/k8s-dns-node-cache:{{nodelocaldns.version}}
  registry: registry.local:5000/dns
  ip: 169.254.20.10
metrics_server:
  enabled: true
  version: v0.7.1
  # {{metrics_server.registry}}/metrics-server:{{metrics_server.version}}
  registry: registry.local:5000/metrics-server
npd:
  enabled: false
  version: v0.8.18
  # {{npd.registry}}/node-problem-detector:{{npd.version}}
  registry: registry.local:5000/node-problem-detector
nvidia_device_plugin:
  enabled: false
  version: v0.15.0
  # {{nvidia_device_plugin.registry}}/k8s-device-plugin:{{nvidia_device_plugin.version}}
  registry: nvcr.io/nvidia

ingress_nginx:
  enabled: true
  version: x.x.x

cert_manager:
  enabled: true
  version: x.x.x

metallb:
  enabled: true
  version: x.x.x
  l2_addr_range: 10.20.183.160-10.20.183.180

prometheus_stack:
  enabled: true
  version: x.x.x

grafana_loki:
  enabled: true
  version: x.x.x
