- name: "Deploy registry-ui from template"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: registry-ui
  block:
    - name: "Template registry-ui yaml"
      template:
        src: registry-ui.yaml.j2
        dest: "{{ k8s_manifests_dir }}/registry-ui.yaml"

    - name: "Apply registry-ui manifest"
      shell: "kubectl -n kube-system apply -f {{ k8s_manifests_dir }}/registry-ui.yaml"
