---
- name: "Check ansible version"
  import_playbook: ansible_version.yml

- name: "Verify Settings"
  hosts: haproxy etcd master worker
  roles:
    - role: verify
      tags: verify

- name: "Generate Certs"
  hosts: localhost
  connection: local
  roles:
    - role: cert
      tags: cert

- name: "Set System Init"
  hosts: haproxy etcd master worker
  roles:
    - role: init
      tags: init

- name: "Set chrony server"
  hosts: haproxy etcd master worker
  roles:
    - role: chrony
      tags: chrony

- name: "Install tools"
  hosts: haproxy etcd master worker
  roles:
    - role: tools
      tags: tools

- name: "Set Container Runtime"
  hosts: master worker
  any_errors_fatal: true
  roles:
    - role: containerd
      tags: containerd

# 使用nerdctl单容器模式实现
- name: "Set Haproxy + Keepalived via nerdctl"
  hosts: master
  roles:
    - role: haproxy-keepalived
      tags: haproxy-keepalived

# 使用宿主机服务
# - name: "Set Haproxy + Keepalived"
#   hosts: haproxy
#   roles:
#     - role: haproxy
#       tags: haproxy
#     - role: keepalived
#       tags: keepalived

- name: "Set Etcd Cluster"
  hosts: etcd
  # 如果出现任何致命错误，立即终止所有task.
  any_errors_fatal: true
  roles:
    - role: etcd
      tags: etcd

- name: "Set Control Plane Nodes"
  hosts: master
  any_errors_fatal: true
  roles:
    - role: master
      tags: master

- name: "Set Worker Nodes"
  hosts: master worker
  any_errors_fatal: true
  roles:
    - role: worker
      tags: worker

- name: "Setup local registry"
  hosts: haproxy etcd master worker
  roles:
    - role: registry
      tags: registry

- name: "Set Container Networking Plugins"
  hosts: master worker
  any_errors_fatal: true
  roles:
    - role: network-plugins
      tags: network-plugins

- name: "Set up kuebernetes storage"
  hosts: master[0]
  roles:
    - role: storage
      tags: storage

- name: "Set Kubernetes Addons"
  hosts: master[0]
  roles:
    - role: addons
      tags: addons
