---
- name: restart etcd
  command: /bin/true
  notify:
    - reload etcd
    - wait for etcd up

- name: reload etcd
  systemd:
    name: etcd
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: false
  register: etcd_restarted


  # TODO:
# - name: wait for etcd up
  # uri:
  #   url: "https://{{ ansible_default_ipv4.address }}:2379/health"
  #   validate_certs: no
  #   client_cert: "/etc/etcd/pki/etcd-healthcheck-client.pem"
  #   client_key: "/etc/etcd/pki/etcd-healthcheck-client.key"
  # register: result
  # until: result.status is defined and result.status == 200
  # retries: 60
  # delay: 1

  # fix: no ssl module
- name: wait for etcd up
  ansible.builtin.shell: |
    curl -k --cert /etc/etcd/pki/etcd-healthcheck-client.pem \
    --key /etc/etcd/pki/etcd-healthcheck-client.key \
    https://{{ ansible_default_ipv4.address }}:2379/health
  register: etcd_health_response
  retries: 60
  delay: 1
  until: etcd_health_response.stdout.find('"health":"true"') != -1
