- name: "Set containerd service"
  template:
    src: "containerd.service.j2"
    dest: "/usr/lib/systemd/system/containerd.service"
    owner: root
    group: root
    mode: 0644
  tags: containerd_config

- name: "reload and restart containerd"
  shell: systemctl daemon-reload && systemctl restart containerd
