---
- name: Replace cert-manager chart image registry
# TODO: use template instead.
  shell: |
    helm uninstall cert-manager -n cert-manager || echo
    cd {{ k8s_manifests_dir }}/charts/cert-manager
    sed -i 's/quay.io/{{ registry.local_registry_url }}/g' values.yaml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: cert-manager

- name: Helm install cert-manager
# backend apply.
  ansible.builtin.shell: |
      nohup helm install cert-manager -n cert-manager --create-namespace --set crds.enabled=true . &
  args:
    chdir: "{{ k8s_manifests_dir }}/charts/cert-manager"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: cert-manager
