---
# --- just for debug.
#     helm uninstall loki -n logging || echo
#     cd {{ k8s_manifests_dir }}/charts/loki
#     sed -i 's/docker.io/{{ registry.local_registry_url }}/g' single-binary-values.yaml
#     sed -i 's/quay.io/{{ registry.local_registry_url }}/g' charts/minio/values.yaml
#     sed -i 's/docker.io/{{ registry.local_registry_url }}/g' values.yaml
#     sed -i 's/quay.io/{{ registry.local_registry_url }}/g' values.yaml
#     sed -i 's/ghcr.io/{{ registry.local_registry_url }}/g' values.yaml
#
#     helm uninstall alloy -n logging || echo
#     cd {{ k8s_manifests_dir }}/charts/alloy
#     sed -i 's/docker.io/{{ registry.local_registry_url }}/g' values.yaml
#     sed -i 's/quay.io/{{ registry.local_registry_url }}/g' values.yaml
#     sed -i 's/ghcr.io/{{ registry.local_registry_url }}/g' values.yaml
#
- name: Uninstall Loki Helm chart
  shell: |
    helm uninstall loki -n logging || echo
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: grafana-loki

- name: Replace image registry in Loki chart values
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: 'docker.io|quay.io|ghcr.io'
    replace: "{{ registry.local_registry_url }}"
  loop:
    - "{{ k8s_manifests_dir }}/charts/loki/single-binary-values.yaml"
    - "{{ k8s_manifests_dir }}/charts/loki/charts/minio/values.yaml"
    - "{{ k8s_manifests_dir }}/charts/loki/values.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: grafana-loki

- name: Uninstall Alloy Helm chart
  shell: |
    helm uninstall alloy -n logging || echo
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: grafana-alloy

- name: Replace image registry in Alloy chart values
  ansible.builtin.replace:
    path: "{{ k8s_manifests_dir }}/charts/alloy/values.yaml"
    regexp: 'docker.io|quay.io|ghcr.io'
    replace: "{{ registry.local_registry_url }}"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: grafana-alloy

- name: Helm install grafana-loki
  ansible.builtin.command:
    cmd: "helm install loki -n logging --create-namespace -f single-binary-values.yaml ."
    chdir: "{{ k8s_manifests_dir }}/charts/loki"
  async: 300
  poll: 0
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: grafana-loki

- name: Helm install grafana-alloy
  ansible.builtin.command:
    cmd: "helm install alloy -n logging --create-namespace ."
    chdir: "{{ k8s_manifests_dir }}/charts/alloy"
  async: 300
  poll: 0
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: grafana-alloy
