---
- name: Uninstall harbor Helm chart.
  shell: |
    helm uninstall harbor -n harbor || echo
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: harbor

- name: Create harbor namespace.
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: harbor
  delegate_to: "{{ groups['master'][0] }}"

- name: Create TLS secret for Harbor.
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: harbor-tls
        namespace: harbor
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ lookup('file', 'certs/k8s.local.crt') | b64encode }}"
        tls.key: "{{ lookup('file', 'certs/k8s.local.key') | b64encode }}"
  delegate_to: "{{ groups['master'][0] }}"

- name: Install harbor via helm.
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    name: harbor
    namespace: harbor
    create_namespace: false
    chart_ref: "{{ k8s_manifests_dir }}/charts/harbor"
    # values_files:
    #   - "{{ role_path }}/templates/values.yaml"
    # wait: true
  delegate_to: "{{ groups['master'][0] }}"
