---
- name: Replace ingress-nginx chart image registry
# TODO: use template instead.
  shell: |
    helm uninstall ingress-nginx -n ingress-nginx || echo
    cd {{ k8s_manifests_dir }}/charts/ingress-nginx
    sed -i 's/registry.k8s.io/{{ registry.local_registry_url }}/g' values.yaml
    sed -i -e '/^\s*digest:/ s/^/#/g' -e '/^\s*digestChroot:/ s/^/#/g' values.yaml
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: ingress-nginx

- name: Helm install ingress-nginx
# backend apply.
  ansible.builtin.shell: |
      nohup helm install ingress-nginx -n ingress-nginx --create-namespace . &
  args:
    chdir: "{{ k8s_manifests_dir }}/charts/ingress-nginx"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: ingress-nginx
