---
- import_tasks: coredns.yml
  tags:
    - coredns

- import_tasks: nodelocaldns.yml
  when: nodelocaldns.enabled == true
  tags:
    - nodelocaldns

- import_tasks: metrics-server.yml
  when: metrics_server.enabled == true
  tags:
    - metrics-server

- import_tasks: node-problem-detector.yml
  when: npd.enabled == true
  tags:
    - node-problem-detector

- import_tasks: nvidia-device-plugin.yml
  when: nvidia_device_plugin.enabled == true
  tags:
    - nvidia_device_plugin

# helm charts below
- name: Copy helm charts tarball to /tmp
  copy:
    src: charts.tar.gz
    dest: "/tmp/charts.tar.gz"
    mode: '0755'
    owner: kube
    group: kube
    remote_src: no
  delegate_to: "{{ groups['master'][0] }}"

- name: Unarchive helm charts tarball to k8s_manifests_dir
  unarchive:
    src: "/tmp/charts.tar.gz"
    dest: "{{ k8s_manifests_dir }}"
    remote_src: yes
  delegate_to: "{{ groups['master'][0] }}"

- import_tasks: ingress-nginx.yml
  when: ingress_nginx.enabled == true
  tags:
    - ingress-nginx

- import_tasks: metallb.yml
  when: metallb.enabled == true
  tags:
    - metallb

- import_tasks: prometheus-stack.yml
  when: prometheus_stack.enabled == true
  tags:
    - prometheus-stack
