---
- import_tasks: coredns.yml
  tags:
    - coredns

- import_tasks: nodelocaldns.yml
  when: nodelocaldns.enabled == true
  tags:
    - nodelocaldns

- name: Include registry-ui role
  include_role:
    name: registry
    tasks_from: registry-ui
  tags: registry-ui

- import_tasks: metrics-server.yml
  when: metrics_server.enabled == true
  tags:
    - metrics-server

- import_tasks: node-problem-detector.yml
  when: npd.enabled == true
  tags:
    - node-problem-detector

- import_tasks: nvidia-device-plugin.yml
  when: nvidia_device_plugin.enabled == true
  tags:
    - nvidia_device_plugin

# helm charts below
- name: Unarchive helm charts tarball directly to k8s_manifests_dir
  unarchive:
    src: charts.tar.gz
    dest: "{{ k8s_manifests_dir }}"
    remote_src: no
    mode: '0755'
    owner: kube
    group: kube
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- import_tasks: ingress-nginx.yml
  when: ingress_nginx.enabled == true
  tags:
    - ingress-nginx

- import_tasks: cert-manager.yml
  when: cert_manager.enabled == true
  tags:
    - cert-manager

- import_tasks: metallb.yml
  when: metallb.enabled == true
  tags:
    - metallb

- import_tasks: grafana-loki.yml
  when: grafana_loki.enabled == true
  tags:
    - grafana-loki

- import_tasks: prometheus-stack.yml
  when: prometheus_stack.enabled == true
  tags:
    - prometheus-stack
