---
- name: "Generate metrics-server yaml"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "metrics-server.yaml.j2", dest: "{{ k8s_manifests_dir }}/metrics-server.yaml"}
  tags: metrics-server

- name: "Deploy metrics-server"
  shell: "kubectl apply -f {{ k8s_manifests_dir }}/metrics-server.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: metrics-server
