---
# --- just for debug.
#  shell: |
#    helm uninstall prometheus-stack -n prometheus-stack || echo
#    cd {{ k8s_manifests_dir }}/charts/kube-prometheus-stack
#    find . -name "values.yaml" -print0 | xargs -0 sed -i -e 's/docker.io/{{ registry.local_registry_url }}/g' -e 's/quay.io/{{ registry.local_registry_url }}/g' -e 's/registry.k8s.io/{{ registry.local_registry_url }}/g'
#
- name: Uninstall prometheus-stack Helm chart
  shell: |
    helm uninstall prometheus-stack -n prometheus-stack || echo
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: prometheus-stack

# - name: Template prometheus-stack values.yaml
#   template:
#     src: prom-stack-values.yaml.j2
#     dest: "{{ k8s_manifests_dir }}/charts/kube-prometheus-stack/values.yaml"
#     mode: '0755'
#     owner: kube
#     group: kube
#   delegate_to: "{{ groups['master'][0] }}"
#   tags: prometheus-stack

- name: Replace image registry in prometheus-stack values files
  ansible.builtin.find:
    paths: "{{ k8s_manifests_dir }}/charts/kube-prometheus-stack"
    patterns: "values.yaml"
    recurse: true
  register: prometheus_values_files
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: prometheus-stack

- name: Update registry URLs in prometheus-stack values.yaml files
  ansible.builtin.replace:
    path: "{{ item.path }}"
    regexp: 'docker.io|quay.io|registry.k8s.io'
    replace: "{{ registry.local_registry_url }}"
  loop: "{{ prometheus_values_files.files }}"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: prometheus-stack

- name: Helm install prometheus-stack
  ansible.builtin.command:
    cmd: "helm install prometheus-stack -n prometheus-stack --create-namespace ."
    chdir: "{{ k8s_manifests_dir }}/charts/kube-prometheus-stack"
  async: 300
  poll: 0
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  ignore_errors: true
  tags: prometheus-stack

- block:
    - name: Unarchive grafana-dashboards-kubernetes tarball directly to k8s_manifests_dir
      unarchive:
        src: grafana-dashboards-kubernetes.tar.gz
        dest: "{{ k8s_manifests_dir }}"
        remote_src: no
        mode: '0755'
        owner: kube
        group: kube
      delegate_to: "{{ groups['master'][0] }}"
      run_once: true

    - name: Install additional grafana kubernetes dashboards
      ansible.builtin.command:
        cmd: "kubectl apply -k {{ k8s_manifests_dir }}/grafana-dashboards-kubernetes -n prometheus-stack"
      delegate_to: "{{ groups['master'][0] }}"
      retries: 20
      delay: 5
      register: additional_dashboard_result
      until: additional_dashboard_result.rc == 0
      ignore_errors: true
      run_once: true
  tags: prometheus-stack
